### ISSUE TITLE
Cannot to join the meeting

### ISSUE THREAD

**Issue by shinjiikari256** [zoom/meetingsdk-linux-raw-recording-sample#1]
Sorry, could you help me?

I'm using your example on my ubuntu 22.04, changing only the config file.

And when connecting to a meeting (planned or new in an android app) I get the status 4 == MEETING_STATUS_DISCONNECTING (MEETING_ERROR_CLIENT_INCOMPATIBLE in docs for Android).
But I am using the current latest SDK libs for linux.

Maybe I'm missing some step not described in the readme.

**Comment by tanchunsiong** [comment]
@shinjiikari256 , please clone the project again. 

Alternatively, to fix this, look at config.txt. There is not supposed to be double quotes for the keys

**Comment by shinjiikari256** [comment]
Oh, thanks, but it didn't work
![image](https://github.com/zoom/meetingsdk-linux-raw-recording-sample/assets/39000784/c13d3a5c-1e65-4998-93bb-dbae0a98a226)

**Comment by tanchunsiong** [comment]
@shinjiikari256 please raise your issue on https://devforum.zoom.us/ and tag me. This might not be the best place for non source code related issues.
