### ISSUE TITLE
Error after executing make in the /demo/build/ folder 

### ISSUE THREAD

**Issue by mva-dev** [zoom/meetingsdk-linux-raw-recording-sample#4]
Hi  @tanchunsiong ,
After executing make in the /demo/build/ folder , I'm getting following error. Please guide me to resolve this. 

azureuser@akzoom-sdkserver:~/meetingsdk-linux-raw-recording-sample/demo/build$ sudo make
Scanning dependencies of target meetingSDKDemo
[  8%] Building CXX object CMakeFiles/meetingSDKDemo.dir/meeting_sdk_demo.cpp.o
/home/azureuser/meetingsdk-linux-raw-recording-sample/demo/meeting_sdk_demo.cpp: In function ‘void JoinMeeting()’:
/home/azureuser/meetingsdk-linux-raw-recording-sample/demo/meeting_sdk_demo.cpp:549:101: error: invalid new-expression of abstract class type ‘Meeting ParticipantsCtrlEventListener’
  549 |  m_pParticipantsController->SetEvent(new MeetingParticipantsCtrlEventListener(&onIsHost, &onIsCoHost));
      |                                                                                                     ^
In file included from /home/azureuser/meetingsdk-linux-raw-recording-sample/demo/meeting_sdk_demo.cpp:37:
/home/azureuser/meetingsdk-linux-raw-recording-sample/demo/MeetingParticipantsCtrlEventListener.h:8:7: note:   because the following virtual functions  are pure within ‘MeetingParticipantsCtrlEventListener’:
    8 | class MeetingParticipantsCtrlEventListener :
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/azureuser/meetingsdk-linux-raw-recording-sample/demo/meeting_sdk_demo.cpp:21:
/home/azureuser/meetingsdk-linux-raw-recording-sample/demo/include/h/meeting_service_components/meeting_participants_ctrl_interface.h:257:15: note:  ‘ virtual void ZOOMSDK::IMeetingParticipantsCtrlEvent::onFocusModeStateChanged(bool)’
  257 |  virtual void onFocusModeStateChanged(bool bEnabled) = 0;
      |               ^~~~~~~~~~~~~~~~~~~~~~~
/home/azureuser/meetingsdk-linux-raw-recording-sample/demo/include/h/meeting_service_components/meeting_participants_ctrl_interface.h:261:15: note:  ‘ virtual void ZOOMSDK::IMeetingParticipantsCtrlEvent::onFocusModeShareTypeChanged(ZOOMSDK::FocusModeShareType)’
  261 |  virtual void onFocusModeShareTypeChanged(FocusModeShareType type) = 0;
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/azureuser/meetingsdk-linux-raw-recording-sample/demo/meeting_sdk_demo.cpp:553:99: error: invalid new-expression of abstract class type ‘MeetingR ecordingCtrlEventListener’
  553 |  m_pRecordController->SetEvent(new MeetingRecordingCtrlEventListener(&onIsGivenRecordingPermission));
      |                                                                                                   ^
In file included from /home/azureuser/meetingsdk-linux-raw-recording-sample/demo/meeting_sdk_demo.cpp:38:
/home/azureuser/meetingsdk-linux-raw-recording-sample/demo/MeetingRecordingCtrlEventListener.h:8:7: note:   because the following virtual functions ar e pure within ‘MeetingRecordingCtrlEventListener’:
    8 | class MeetingRecordingCtrlEventListener :public IMeetingRecordingCtrlEvent
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/azureuser/meetingsdk-linux-raw-recording-sample/demo/include/h/meeting_service_components/meeting_participants_ctrl_interf ace.h:9,
                 from /home/azureuser/meetingsdk-linux-raw-recording-sample/demo/meeting_sdk_demo.cpp:21:
/home/azureuser/meetingsdk-linux-raw-recording-sample/demo/include/h/meeting_service_components/meeting_recording_interface.h:120:15: note:     ‘virtu al void ZOOMSDK::IMeetingRecordingCtrlEvent::onCloudRecordingStorageFull(time_t)’
  120 |  virtual void onCloudRecordingStorageFull(time_t gracePeriodDate) = 0;
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/meetingSDKDemo.dir/build.make:63: CMakeFiles/meetingSDKDemo.dir/meeting_sdk_demo.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/meetingSDKDemo.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by harshadk-sourcefuse** [comment]
i am also facing the same issue, did you find any solution?

**Comment by tanchunsiong** [comment]
@mva-dev @harshadk-sourcefuse the current build supports 5.16.10
I'll be updating the code to support the latest SDK in a bit

**Comment by tanchunsiong** [comment]
@harshadk-sourcefuse @mva-dev ,

the code has been updated to support the latest SDK. 

please pull the latest code and try again

**Comment by harshadk-sourcefuse** [comment]
> @harshadk-sourcefuse @mva-dev ,
> 
> the code has been updated to support the latest SDK.
> 
> please pull the latest code and try again

thanks, will check

**Comment by mva-dev** [comment]
@tanchunsiong Thank you so much. Its working now . 
After executing make in the /demo/build/ directory to compile , meetingSDKDemo file got generated in the /meetingsdk-linux-raw-recording-sample/demo/bin/  folder. But I'm not able to join the meeting. Also please help me to understand how to get the recording token . I read relevant docs , but I'm not understanding. Please help me out .

**Comment by harshadk-sourcefuse** [comment]
Hello @tanchunsiong, 
I would like to understand how to generate a recording token programmatically, rather than passing it through the config.text. Specifically, I want to create the recording token before the bot joins the meeting and then set it in the configuration. Any guidance on achieving this would be appreciated

**Comment by tanchunsiong** [comment]
closing this @mva-dev @harshadk-sourcefuse as the issue page should not be used for technical support.
I'll be happy to help you out at the dev forum, do tag in after you create a thread.
https://devforum.zoom.us/
